### ISSUE TITLE
Extend block IDs?

### ISSUE THREAD

**Issue by labpaw** [HxCKDMS/HxCCore#2]
Just saw that this mod extends enchantment ids. Is it possible to extend block IDs? I saw one guy installed a lot of mods and all block IDs were loaded(yes it was on MC 1.7.10). He got something like this in log: "There was a severe problem during mod loading that has caused the game to fail
cpw.mods.fml.common.LoaderException: java.lang.RuntimeException: Invalid id 10229 - maximum id range exceeded." Just close it if it impossible or doesn't fit this mod.

**Comment by DrZed** [comment]
I don't really know about the block id range never really touched it. My Co-Owner says it is possible but thing is I don't think any mod is using numerical IDs any more thus if you run into that problem you have too many items in your pack because forge gives them a number when it is running.

I will look into expanding it by 2x or maybe longer if needed.

**Comment by labpaw** [comment]
Yeah, IDs no longer numerical but they still limited to only 4096 blocks. Check this: https://github.com/MinecraftForge/FML/blob/9c3013e02af1bd2f724d34a30e0b880b6e131645/src/main/java/net/minecraftforge/fml/common/registry/GameData.java#L65 So, there are no more conflicts but IDs still limited to 4096. It will be enough to expand them to 2x. Thanks.

**Comment by DrZed** [comment]
Yeah I know how it is my Co-Owner is in call and my screen is always his TV so he watches me code and respond to things like this. lel Anyway he already said and showed. We may be able to do It but it will be difficult since it isn't private or anything it is just static final we will try using an Access transformer to give it public access then using reflection set the final to a higher value
